/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    _Temp: typeof import('./src/components/_Temp.vue')['default']
    ChangeRate: typeof import('./src/components/ChangeRate.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElText: typeof import('element-plus/es')['ElText']
    Json: typeof import('./src/components/Json.vue')['default']
    TimeConvert: typeof import('./src/components/TimeConvert.vue')['default']
    Uuid: typeof import('./src/components/Uuid.vue')['default']
  }
}
